# Generated by Django 2.0.5 on 2018-09-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wheel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=150, verbose_name='图片')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('trackid', models.CharField(max_length=20, verbose_name='商品编号')),
                ('isDwlete', models.BooleanField(default=False, verbose_name='逻辑删除')),
            ],
        ),
    ]
