# Generated by Django 2.0.5 on 2018-09-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='isDwlete',
            field=models.NullBooleanField(default=False, verbose_name='逻辑删除'),
        ),
    ]
