# Generated by Django 2.0.5 on 2018-09-02 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0002_auto_20180902_2222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=150, verbose_name='图片')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('trackid', models.CharField(max_length=20, verbose_name='导航编号')),
                ('isDwlete', models.NullBooleanField(default=False, verbose_name='逻辑删除')),
            ],
        ),
    ]
